SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS attendances;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS ref_shifts;
DROP TABLE IF EXISTS ref_departments;

SET FOREIGN_KEY_CHECKS = 1;